import { DigestItem, GeneratedArticle } from '@/types';

function nowIso() {
  return new Date().toISOString();
}

function id(prefix: string) {
  return `${prefix}_${Math.random().toString(36).slice(2)}_${Date.now().toString(36)}`;
}

const generatedAt = nowIso();

const seedArticles: GeneratedArticle[] = [
  {
    id: id('seed'),
    slug: 'welcome-to-autopress-editorial-engine',
    headline: 'Welcome to AutoPress: an AI-native editorial engine',
    subheadline:
      'This is a seeded report included so the homepage renders on first deploy. Use /api/refresh to generate today’s live coverage once env vars are set.',
    isFullReport: true,
    body:
      'AutoPress is an AI-native news surface designed around reporting-quality articles, produced via an automated pipeline. In production deployments, serverless runtimes can cold-start with no cached output; to avoid an empty publication, this seeded report ships with the app.\n\nTo generate fresh coverage, configure your environment variables on Vercel (NewsAPI + model provider), then trigger the long-running pipeline via the refresh endpoint. The resulting reports will appear across the homepage, digest, and article pages.\n\nThis seed is intentionally transparent: it is not a live news report, but a demo safeguard to ensure the site is functional immediately after deployment.',
    keyPoints: [
      'A seeded article is bundled so the homepage never renders empty on cold deploys.',
      'Real reports are generated by the pipeline via /api/refresh once env vars are configured.',
      'Every generated report cites its sources and includes editorial metadata.',
    ],
    readTime: 3,
    tags: ['AutoPress', 'Demo', 'Editorial Engine'],
    sourceStories: [
      {
        title: 'AutoPress README / submission context',
        source: 'AutoPress',
        url: '',
      },
    ],
    generatedAt,
    category: 'world',
    imageUrl: null,
    editorialPriority: 'analysis',
    timeline: [
      { date: new Date().toISOString().slice(0, 10), event: 'Seed report bundled with deployment' },
    ],
    impact: 'global',
    pullQuote: 'Seed content keeps the publication readable on first deploy.',
    confidenceScore: 0.6,
    wordCount: 260,
    trendVelocity: 'steady',
    viralSnapshot: [
      'Seed report bundled with the deploy',
      'Prevents blank homepage on serverless cold start',
      'Trigger /api/refresh for live reports',
    ],
    angle: 'Why seed content exists on serverless deployments.',
    context:
      'Serverless functions may not persist disk state and may not complete background work after responding. A bundled seed avoids an empty UI.',
    stakeholders: ['Readers', 'Operators', 'Vercel runtime'],
    keyQuestions: ['Are production env vars configured?', 'Has /api/refresh been triggered recently?'],
    talkingPoints: ['Seed prevents blank state', 'Refresh generates live reports'],
  },
];

const seedDigest: DigestItem[] = [
  {
    id: id('seed_digest'),
    headline: 'Getting started',
    summary: 'Set env vars on Vercel, then call /api/refresh to generate live reports.',
    category: 'world',
  },
];

export const SEED_STORE = {
  articles: seedArticles,
  digest: seedDigest,
  generatedAt,
};

